// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO99TDZzCpo-nlNS9SwdZWJ1jO0eky3qs',
    appId: '1:541358957685:web:bd5aa63eda89e45bb1843c',
    messagingSenderId: '541358957685',
    projectId: 'dash-app-ffc85',
    authDomain: 'dash-app-ffc85.firebaseapp.com',
    storageBucket: 'dash-app-ffc85.appspot.com',
    measurementId: 'G-R4TB9NPPJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yzJbErRYUHeN6Y0FFcaKLJaFtnCCNQw',
    appId: '1:541358957685:android:6feba6cc9fd96b7bb1843c',
    messagingSenderId: '541358957685',
    projectId: 'dash-app-ffc85',
    storageBucket: 'dash-app-ffc85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4QMS7ywhfhcZAD8b4IN1qKEr4bTpwgEk',
    appId: '1:541358957685:ios:812e0d29bae3d377b1843c',
    messagingSenderId: '541358957685',
    projectId: 'dash-app-ffc85',
    storageBucket: 'dash-app-ffc85.appspot.com',
    iosClientId: '541358957685-g0049f6je7tlfhmdvfjcv437o4u65pq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4QMS7ywhfhcZAD8b4IN1qKEr4bTpwgEk',
    appId: '1:541358957685:ios:812e0d29bae3d377b1843c',
    messagingSenderId: '541358957685',
    projectId: 'dash-app-ffc85',
    storageBucket: 'dash-app-ffc85.appspot.com',
    iosClientId: '541358957685-g0049f6je7tlfhmdvfjcv437o4u65pq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashApp',
  );
}
